version: '{build}-{branch}'
image: Visual Studio 2017

branches:
  # whitelist
  only:
    - master

clone_depth: 50


init:
- ps: |
    function craft() {
        & "C:\Python37-x64\python.exe" "C:\CraftMaster\CraftMaster\CraftMaster.py" --config "$env:APPVEYOR_BUILD_FOLDER\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $env:TARGET -c $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --depth=1 https://github.com/KDE/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    craft craft
    craft --install-deps gammaray

build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER gammaray

after_build:
- ps: |
    if ($env:TARGET -eq "windows-msvc2017_64-cl") {
        craft --add-blueprint-repository [git]https://github.com/KDAB/craft-blueprints-kdab.git
        craft --no-cache gammaray-binary-probes
        craft nsis
    }
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER --package gammaray

#test_script:
#- ps: |
   #craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER --test gammaray
test: off

environment:
    matrix:
    - TARGET: windows-msvc2017_32-cl
    - TARGET: windows-msvc2017_64-cl

artifacts:
  - path: cache\**\.*
  - path: binaries\*

deploy:
    - provider: Environment
      name: GammaRay
